language: go
sudo: false
go:
  - 1.4
  - 1.5.4
  - 1.6.4
  - 1.7.4
  - tip

services:
  - docker

before_install:
- docker run -d --name redis -p 6379:6379 redis:alpine
- docker run -d --name mongo -p 27017:27017 mvertes/alpine-mongo

script:
  - go test -v middleware/*.go
  - go test -v v1/*.go
