language: go
sudo: false
go:
  - 1.7.x
  - 1.8.x
  - tip

services:
  - redis-server
  - mongodb

# before_install:
# - docker run -d --name redis -p 6379:6379 redis:alpine
# - docker run -d --name mongo -p 27017:27017 mvertes/alpine-mongo

script:
  - go test -v middleware/*.go
  - go test -v v1/*.go
